server:
  port: 8058

spring:
  application:
    name: file-storage-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/design-service
    username: root
    password: mysql25
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
